services:
  focalboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: focalboard-local:latest
    ports:
      - "8000:8000"
    volumes:
      - fbdata:/opt/focalboard/data
    restart: unless-stopped

volumes:
  fbdata:
