version: "3.9"

services:
  app:
    extends:
      file: ../docker-compose.yml
      service: focalboard
    container_name: focalboard
    ports:
      - "80:8000"
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000
